document.writeln("<div class=\'tab-pane fade  in active\'>");
document.writeln("<br>");
document.writeln("");
document.writeln(" <h2><a href=\'/product/2017-10-11/3.html\'><span style=\'text-decoration:underline\'>*S SERIES SPRING CONE CRUSHER</span></a></h2>");
document.writeln("");
document.writeln("");
document.writeln("<p><br>");
document.writeln("<strong>WEIGHTS OF S SERIES CRUSHER &nbsp;&nbsp;( KG )</strong><br>");
document.writeln("&nbsp;</p>");
document.writeln("<table align=\'center\' class=\'table table-bordered\' height=\'67\' width=\'736\'>");
document.writeln("    <tbody>");
document.writeln("        <tr>");
document.writeln("            <td style=\'width: 146px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td colspan=\'4\' style=\'width: 305px; text-align: center;\'>STANDARD</td>");
document.writeln("            <td colspan=\'4\' style=\'width: 305px; text-align: center;\'>SHORT HEAD</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td style=\'width: 146px; text-align: center;\'>CRUSHER SIZE</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>SY90B</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>SY185B</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>SY280B</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>SY400B</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>SY90D</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>SY185D</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>SY28D</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>SY400D</td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td style=\'width: 146px; text-align: center;\'>Crusher Complete</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>10600</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>23000</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>45000</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>900000</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>10600</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>23000</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>45000</td>");
document.writeln("            <td style=\'width: 76px; text-align: center;\'>92500</td>");
document.writeln("        </tr>");
document.writeln("    </tbody>");
document.writeln("</table>");
document.writeln("<br>");
document.writeln("<br>");
document.writeln("CAVITY SHAPE, FEED OPENING, PRODUCT SIZE AND PRODUCTION CAPACITY OF SY SERIES SHORT HEAD CONE CRUSHER<br>");
document.writeln("OPEN CIRCUIT-----CRUSHER PRODUCTION CAPACITY AT INDICATED DISCHARGE SETTING &nbsp;&nbsp;( t/h )<br>");
document.writeln("&nbsp;<br>");
document.writeln("<table align=\'center\' class=\'table table-bordered\' height=\'67\' width=\'736\'>");
document.writeln("    <tbody>");
document.writeln("        <tr>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 69px; text-align: center;\'><strong>Crusher Size</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 91px; text-align: center;\'><strong>Cavity Shape</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 111px; text-align: center;\'><strong>Suggested Minimum Discharge Setting</strong></td>");
document.writeln("            <td colspan=\'2\' style=\'width: 174px; text-align: center;\'><strong>Feed Opening With Minimum Suggested Discharge Setting</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 67px; text-align: center;\'><strong>3mm</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 67px; text-align: center;\'><strong>5mm</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 67px; text-align: center;\'><strong>6mm</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 67px; text-align: center;\'><strong>10mm</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 67px; text-align: center;\'><strong>13mm</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 67px; text-align: center;\'><strong>16mm</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 67px; text-align: center;\'><strong>19mm</strong></td>");
document.writeln("            <td colspan=\'1\' rowspan=\'2\' style=\'width: 67px; text-align: center;\'><strong>25mm</strong></td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>Closed Side</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>Open Side</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td colspan=\'1\' rowspan=\'3\' style=\'width: 69px; text-align: center;\'><strong>SY90D</strong></td>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Fine</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>3mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>13mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>41mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>31</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>47</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>62</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>78</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>104</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Medium</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>3mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>33mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>60mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>31</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>47</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>62</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>78</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>104</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>115</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Coarse</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>6mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>51mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>76mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>67</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>83</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>109</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>129</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>146</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td colspan=\'1\' rowspan=\'4\' style=\'width: 69px; text-align: center;\'><strong>SY185D</strong></td>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Fine</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>3mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>29mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>64mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>41</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>67</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>94</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>119</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>156</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>187</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Medium</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>6mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>54mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>89mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>94</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>119</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>156</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>187</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Coarse</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>8mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>70mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>105mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>125</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>182</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>208</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>230</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>261</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Extra Coarse</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>16mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>98mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>133mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>239</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>271</td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td colspan=\'1\' rowspan=\'4\' style=\'width: 69px; text-align: center;\'><strong>SY280D</strong></td>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Fine</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>5mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>35mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>70mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>103</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>156</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>187</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>239</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Medium</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>6mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>54mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>89mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>156</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>187</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>239</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>292</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>322</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Coarse</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>10mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>98mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>133mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>218</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>292</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>322</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>354</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>385</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Extra Coarse</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>13mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>117mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>133mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>292</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>322</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>354</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>385</td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td colspan=\'1\' rowspan=\'4\' style=\'width: 69px; text-align: center;\'><strong>SY400D </strong></td>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Fine</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>5mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>51mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>105mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>218</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>308</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>372</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>408</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>463</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Medium</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>10mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>95mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>133mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>404</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>463</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>517</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>580</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("        </tr>");
document.writeln("        <tr>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Coarse</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>13mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>127mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>178mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>517</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>540</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>621</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>680</td>");
document.writeln("        </tr>");
document.writeln("        <tr class=\'warning\'>");
document.writeln("            <td style=\'width: 91px; text-align: center;\'>Extra Coarse</td>");
document.writeln("            <td style=\'width: 111px; text-align: center;\'>16mm</td>");
document.writeln("            <td style=\'width: 89px; text-align: center;\'>152mm</td>");
document.writeln("            <td style=\'width: 85px; text-align: center;\'>203mm</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>&nbsp;</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>580</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>671</td>");
document.writeln("            <td style=\'width: 67px; text-align: center;\'>744</td>");
document.writeln("        </tr>");
document.writeln("    </tbody>");
document.writeln("</table>");
document.writeln("<br>");
document.writeln("&nbsp;</div>");